# List gelaja yang mungkin pada kerusakan laptop beserta penjelasan
SYMPTOM_LABELS = {
    "laptop_tidak_menyala": "Laptop tidak bisa menyala sama sekali",
    "lampu_indikator_mati": "Lampu indikator daya mati total",
    "lampu_indikator_menyala": "Lampu indikator daya menyala (ada tanda daya masuk)",
    "tidak_ada_suara": "Tidak ada suara apapun saat tombol power ditekan",
    "ada_suara_kipas": "Terdengar suara kipas berputar setelah dinyalakan",
    "laptop_menyala": "Laptop menyala (ada aktivitas, fan berputar, suara startup)",
    "layar_hitam": "Layar tetap hitam setelah laptop dinyalakan",
    "laptop_lambat": "Laptop sangat lambat saat digunakan",
    "sering_hang": "Laptop sering mengalami hang / not responding",
    "hard_disk_berbunyi": "Hard disk mengeluarkan bunyi aneh (klik atau dengung tidak normal)",
    "hard_disk_tidak_berbunyi": "Hard disk tidak mengeluarkan bunyi aneh",
    "laptop_panas_berlebih": "Laptop terasa sangat panas saat digunakan",
    "sering_mati_sendiri": "Laptop sering mati sendiri tanpa peringatan",
    "keyboard_tidak_berfungsi": "Keyboard tidak berfungsi sama sekali",
    "beberapa_tombol_tidak_merespons": "Beberapa tombol keyboard tidak merespons",
    "wifi_tidak_terdeteksi": "WiFi tidak terdeteksi di daftar jaringan",
    "bluetooth_tidak_berfungsi": "Bluetooth tidak bisa diaktifkan",
    "baterai_tidak_mengisi": "Baterai tidak bertambah persentasenya meski charger terhubung",
    "adaptor_terhubung": "Adaptor/charger sudah terhubung ke laptop",
    "layar_bergaris": "Layar menampilkan garis-garis horizonta atau vertikal",
    "warna_tidak_normal": "Warna tampilan layar tidak normal atau ada artefak visual",
    "sering_restart_sendiri": "Laptop sering restart sendiri secara tiba-tiba",
    "bsod": "Muncul layar biru (Blue Screen of Death / BSOD)",
    "touchpad_tidak_merespons": "Touchpad tidak merespons sama sekali",
}

# Aturan
RULES = [
    {
        "id": "R01",
        "conditions": ["laptop_tidak_menyala", "lampu_indikator_mati", "tidak_ada_suara"],
        "cause": "Kerusakan pada baterai atau adaptor daya",
        "solution": "Periksa dan ganti adaptor daya. Coba charger lain. Jika masalah berlanjut, ganti sel baterai.",
        "cf_he": 0.9,
    },
    {
        "id": "R02",
        "conditions": ["laptop_tidak_menyala", "lampu_indikator_menyala"],
        "cause": "Kerusakan pada layar (LCD/backlight) atau koneksi kabel layar",
        "solution": "Hubungkan ke monitor eksternal. Jika layar eksternal normal, ganti kabel layar atau panel LCD.",
        "cf_he": 0.85,
    },
    {
        "id": "R03",
        "conditions": ["laptop_menyala", "layar_hitam", "ada_suara_fan"],
        "cause": "Kerusakan RAM atau RAM tidak terpasang dengan benar",
        "solution": "Lepas dan pasang kembali RAM. Coba dengan satu keping RAM bergantian. Ganti RAM jika perlu.",
        "cf_he": 0.8,
    },
    {
        "id": "R04",
        "conditions": ["laptop_lambat", "sering_hang", "hard_disk_berbunyi"],
        "cause": "Hard disk mengalami bad sector atau hampir rusak (HDD failure)",
        "solution": "Backup data segera. Jalankan disk check (chkdsk). Ganti HDD atau upgrade ke SSD.",
        "cf_he": 0.9,
    },
    {
        "id": "R05",
        "conditions": ["laptop_lambat", "sering_hang", "hard_disk_tidak_berbunyi"],
        "cause": "RAM tidak mencukupi atau terlalu banyak proses di background",
        "solution": "Tutup program yang tidak perlu. Periksa Task Manager. Tambah kapasitas RAM. Nonaktifkan startup programs.",
        "cf_he": 0.65,
    },
    {
        "id": "R06",
        "conditions": ["laptop_panas_berlebih", "sering_mati_sendiri"],
        "cause": "Sistem pendingin bermasalah — fan tersumbat debu atau thermal paste kering",
        "solution": "Bersihkan heatsink dan fan dari debu. Ganti thermal paste pada prosesor dan GPU.",
        "cf_he": 0.88,
    },
    {
        "id": "R07",
        "conditions": ["keyboard_tidak_berfungsi", "beberapa_tombol_tidak_merespons"],
        "cause": "Kerusakan fisik keyboard atau driver keyboard bermasalah",
        "solution": "Update atau reinstall driver keyboard. Coba keyboard eksternal via USB. Jika masalah persisten, ganti keyboard.",
        "cf_he": 0.7,
    },
    {
        "id": "R08",
        "conditions": ["wifi_tidak_terdeteksi", "bluetooth_tidak_berfungsi"],
        "cause": "Kartu WiFi/Bluetooth rusak atau driver wireless tidak terinstall dengan benar",
        "solution": "Reinstall driver wireless dari situs produsen. Jika gagal setelah reinstall, ganti kartu WiFi.",
        "cf_he": 0.75,
    },
    {
        "id": "R09",
        "conditions": ["baterai_tidak_mengisi", "adaptor_terhubung"],
        "cause": "Kerusakan IC charging, port charger longgar, atau baterai sudah habis siklus",
        "solution": "Periksa kondisi port charger. Coba adaptor lain. Kalibrasi baterai. Bawa ke teknisi untuk pengecekan IC charging.",
        "cf_he": 0.8,
    },
    {
        "id": "R10",
        "conditions": ["layar_bergaris", "warna_tidak_normal"],
        "cause": "Kerusakan panel LCD atau GPU bermasalah",
        "solution": "Hubungkan ke monitor eksternal. Jika monitor eksternal normal → ganti panel LCD. Jika monitor eksternal juga bergaris → GPU bermasalah, perlu re-soldering atau penggantian.",
        "cf_he": 0.82,
    },
    {
        "id": "R11",
        "conditions": ["laptop_menyala", "sering_restart_sendiri", "bsod"],
        "cause": "Driver bermasalah, RAM rusak, atau infeksi malware",
        "solution": "Jalankan Windows Memory Diagnostic. Update semua driver. Scan malware. Jika BSOD persisten, reinstall OS.",
        "cf_he": 0.7,
    },
    {
        "id": "R12",
        "conditions": ["touchpad_tidak_merespons", "laptop_menyala"],
        "cause": "Driver touchpad bermasalah atau touchpad terkunci (Fn lock)",
        "solution": "Coba tekan Fn + F7 (atau tombol touchpad toggle). Reinstall driver touchpad dari Device Manager.",
        "cf_he": 0.72,
    },
]

# Alasan dari masing-masing gejala sebagai kejelasan sistem pakar
WHY_NOTES = {
    "laptop_tidak_menyala": "Menentukan apakah masalah ada di sistem daya atau di komponen lain.",
    "lampu_indikator_mati": "Jika indikator mati, berarti tidak ada daya sama sekali masuk ke sistem — menunjuk ke adaptor atau baterai.",
    "lampu_indikator_menyala": "Jika indikator menyala tapi layar hitam, berarti daya ada tetapi output display bermasalah.",
    "tidak_ada_suara": "Tidak ada suara berarti tidak ada proses booting — komponen daya kemungkinan gagal total.",
    "ada_suara_fan": "Suara fan membuktikan laptop mendapat daya dan CPU aktif — masalah ada di display atau RAM, bukan daya.",
    "laptop_menyala": "Konfirmasi bahwa sistem daya bekerja — penyebab kerusakan ada di komponen lain.",
    "layar_hitam": "Layar hitam dengan tanda daya aktif biasanya menunjukkan masalah RAM (gagal POST) atau display.",
    "laptop_lambat": "Kelambatan sistemik biasanya berasal dari storage atau RAM, bukan CPU.",
    "sering_hang": "Hang berulang menunjukkan bottleneck di RAM, storage, atau terlalu banyak proses.",
    "hard_disk_berbunyi": "Bunyi klik atau grinding pada HDD adalah tanda mekanis bahwa disk akan segera gagal.",
    "hard_disk_tidak_berbunyi": "Tanpa bunyi HDD, masalah kelambatan lebih mungkin berasal dari RAM atau software.",
    "laptop_panas_berlebih": "Suhu berlebih memicu thermal throttling dan shutdown otomatis untuk melindungi CPU.",
    "sering_mati_sendiri": "Shutdown mendadak tanpa peringatan hampir selalu disebabkan oleh thermal protection yang aktif.",
    "keyboard_tidak_berfungsi": "Keyboard mati total membutuhkan pemeriksaan driver sebelum langsung mengganti hardware.",
    "beberapa_tombol_tidak_merespons": "Kegagalan sebagian tombol biasanya fisik (koneksi membrane) atau driver.",
    "wifi_tidak_terdeteksi": "WiFi tidak terdeteksi sama sekali (bukan sekadar tidak tersambung) menunjukkan masalah driver atau hardware kartu wireless.",
    "bluetooth_tidak_berfungsi": "Bluetooth dan WiFi biasanya berada di satu kartu yang sama — keduanya gagal memperkuat indikasi kerusakan kartu.",
    "baterai_tidak_mengisi": "Baterai tidak mengisi meski charger terhubung menunjukkan masalah di sisi charging circuit, bukan hanya baterai.",
    "adaptor_terhubung": "Konfirmasi bahwa charger memang terhubung — diperlukan untuk memastikan gejala bukan karena lupa colok.",
    "layar_bergaris": "Garis pada layar bisa dari panel LCD rusak atau output GPU bermasalah — perlu dibedakan dengan monitor eksternal.",
    "warna_tidak_normal": "Artefak warna yang tidak normal memperkuat kemungkinan kerusakan GPU atau panel display.",
    "sering_restart_sendiri": "Restart paksa berulang bisa dari driver crash, RAM gagal, atau malware.",
    "bsod": "BSOD memberikan error code yang spesifik — hampir selalu terkait driver, RAM, atau OS corruption.",
    "touchpad_tidak_merespons": "Touchpad mati bisa sesederhana Fn lock atau serius seperti konektor rusak.",
}

ALL_SYMPTOMS = sorted(set(s for rule in RULES for s in rule["conditions"]))
